export const SITE_CONFIG = {
  name: "おかずNavi",
  title: "おかずNavi | 同人誌・エロ漫画の新作発見サイト",
  description:
    "同人誌・エロ漫画の新作発見サイト。FANZA・DLsiteの人気作品ランキング、注目作者の最新作をいち早くお届け。質の高いアダルト作品を安全に購入できる正規サイトへご案内します。",
  keywords: [
    "同人誌",
    "エロ漫画",
    "アダルト",
    "新作",
    "ランキング",
    "FANZA",
    "DLsite",
    "正規購入",
    "安全ダウンロード",
    "人気作者",
    "二次元",
    "成人向け",
    "R18",
    "同人作品",
    "エロ同人",
  ],
  author: "おかずNavi",
  url: "https://okazu-navi.com",
  siteName: "おかずNavi",
  locale: "ja_JP",
  themeColor: "#FF6B6B",
} as const;
